version: '3.8'

services:
  nginx:
    image: nginx
    container_name: nginx_container
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - /host/nginx:/usr/share/nginx/html
    deploy:
      resources:
        limits:
          cpus: '1.0'
          memory: 512M

  clickhouse:
    image: yandex/clickhouse-server
    container_name: clickhouse_container
    restart: unless-stopped
    ports:
      - "8123:8123"
      - "9000:9000"
    volumes:
      - /host/clickhouse:/var/lib/clickhouse
    deploy:
      resources:
        limits:
          cpus: '2.0'
          memory: 1G
